Chore: Add new requirements

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -19,6 +19,20 @@ jobs:
       - run: flake8 app/
       - run: bandit -r app/ --skip B101
 
+      - name: Run Flask app in background
+        run: |
+          nohup python -m flask run --host=127.0.0.1 --port=5000 &
+          sleep 5  # espera que arranque la app
+      - name: Test /health endpoint
+        run: |
+          RESPONSE=$(curl --write-out "%{http_code}" --silent --output /dev/null http://127.0.0.1:5000/health)
+          if [ "$RESPONSE" != "200" ]; then
+            echo "Health check failed with status $RESPONSE"
+            exit 1
+          else
+            echo "Health check passed"
+          fi
+
   docker-build:
     needs: build-and-test
     runs-on: ubuntu-latest
